import turtle
t = turtle.Turtle()
t.speed(10)
turtle.bgcolor("black")
t.color("orange")
t.begin_fill()
t.circle(100)
t.end_fill()
t.penup()
t.goto(-20, 150)
t.pendown()
t.color("green")
t.begin_fill()
t.setheading(90)
t.forward(40)
t.right(90)
t.forward(40)
t.right(90)
t.forward(40)
t.end_fill()
t.penup()
t.goto(0, 100)
t.pendown()
t.color("darkorange")
for angle in [-40, -20, 0, 20, 40]:
    t.penup()
    t.goto(0, 100)
    t.setheading(-90 + angle)
    t.pendown()
    t.circle(100, 60)
t.penup()
t.goto(-40, 60)
t.color("black")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(30, 60)
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(-25, 30)
t.setheading(-60)
t.begin_fill()
for i in range(3):
    t.forward(50)
    t.left(120)
t.end_fill()
t.hideturtle()
turtle.done()
